stages:
    - build
    - lint
    - test
    - deploy

composer:
    stage: build
    artifacts:
        name: "$CI_JOB_NAME"
        untracked: true
        expire_in: "2 days"
        paths:
            - vendor/
    tags:
        - composer
        - php-8.4
    only:
        - branches
        - tags
        - pushes
        - merge_requests
    script:
        - "make composer-version"
        - "make composer-install"
        - "make composer-autoload"

lint:
    stage: lint
    dependencies:
        - composer
    tags:
        - test
        - php-8.4
    only:
        - branches
        - tags
        - pushes
        - merge_requests
    script:
        - make lint

phpunit:
    stage: test
    dependencies:
        - composer
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - build/logs/junit.xml
            - build/logs/clover.xml
            - build/logs/crap4j.xml
            - build/coverage/
        expire_in: "2 weeks"
    tags:
        - xdebug
        - test
        - php-7.2
    only:
        - tags
    script:
        - make phpunit

satis-update:
    stage: deploy
    script:
        - cd /var/webshare/satis.home.segnitz.net/ && /var/webshare/satis.home.segnitz.net/bin/satis build -n /var/webshare/satis.home.segnitz.net/satis.json /var/webshare/satis.home.segnitz.net/web/private "soarce/client"
    tags:
        - deploy
        - homeip
    when: always
